### ISSUE TITLE
Issues with the Adversary template importer

### ISSUE THREAD

**Issue by Tousandsons** [Aliharu/Foundry-Ex3#15] opened 2022-10-06 19:26 UTC
Hello,

I'm following the template format do import adversaries, but I'm experiencing some probles.

One I was able to find a fix: The merits line kept showing a failed on line text message, nut I was able to bypass it using the word "Merit", instead of "Merits".

The seconfd one os with the attack line. No matter how many variables I use, I keep getting the failed on line text.
Example of text used: Attack (Unarmed): 8 dice (Damage 8); Tags: Bashing, Brawl, Grappling, Natural

Thanks in advance
![screen](https://user-images.githubusercontent.com/115185509/194401519-0d0d3404-a925-418c-b7a7-3f208d518a8b.png)

**Comment by Aliharu** [comment] 2022-10-09 17:06
Okay so the issue is actually with Martial Arts.

Remove Martial Arts (Dreaming Pearl Courtesan) 4 from the list and change "Merit" back to "Merits" should fix the issue.  Your stat block for Adeimantus than the one i see in the book however so i cannot guarantee it will work

Ill have fixes for this issue up at a later date but for now you will have to add martial arts manually.

**Comment by Tousandsons** [comment] 2022-10-09 18:51
Thanks.

It is indeed different stats. When the original one didn't work I changed
for a simpler one to see if it would work that way.

Will try with your fixes now.

Awesome work btw!

Thank you very much

Em dom., 9 de out. de 2022 14:07, Aliharu ***@***.***>
escreveu:

**Comment by Aliharu** [comment] 2022-10-09 19:41
Okay the issue should be fixed in 1.0.4

**Closed by Aliharu** 2022-10-09 19:41 UTC
